//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCar
    {
        public int ID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<long> CMND { get; set; }
        public Nullable<int> ThueBaoNhieuNgay { get; set; }
        public Nullable<long> TienDatCoc { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> IDChiTietDV { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
