//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public int MaDV { get; set; }
        public string TenDV { get; set; }
        public string MoTa { get; set; }
        public string Hinh { get; set; }
    }
}
