//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DichVuCamDoThueXeEntities : DbContext
    {
        public DichVuCamDoThueXeEntities()
            : base("name=DichVuCamDoThueXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BookCar> BookCars { get; set; }
        public virtual DbSet<ChiTietDV> ChiTietDVs { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<GetMail> GetMails { get; set; }
        public virtual DbSet<GroupAccount> GroupAccounts { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinMail> ThongTinMails { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
    }
}
